apiVersion: v1
kind: Service
metadata:
  name: treatment-monitor-api
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "treatment-monitor-api"
  
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7000
  selector:
    app: treatment-monitor-api
  type: LoadBalancer
