apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-monitor-api-deployment
  labels:
    app: treatment-monitor-api
  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: treatment-monitor-api
  template:
    metadata:
      labels:
        app: treatment-monitor-api
    spec:
      containers:
        - name: treatment-monitor-api
          image: bartee/treatment-monitor-api:1.0.4
          ports:
            - containerPort: 7000
              name: http
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: treatment-monitor-secret
                  key: dbConnectionString
            - name: APP_HOST
              valueFrom:
                secretKeyRef:
                  name: treatment-monitor-secret
                  key: appHost

    