apiVersion: v1
kind: Service
metadata:
  name: treatment-monitor-app
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "treatment-monitor"
  
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4200
  selector:
    app: treatment-monitor-app
  type: LoadBalancer
