apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-monitor-app-deployment
  labels:
    app: treatment-monitor-app

spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: treatment-monitor-app

  template:
    metadata:
      labels:
        app: treatment-monitor-app
    spec:
      containers:
        - name: treatment-monitor-app
          image: bartee/treatment-monitor-app:1.0.2
          ports:
            - containerPort: 4200
              name: http
